{"totales": 2, 
"promociones": 
	[
	{"status": "publish", 
	"orden": 1, 
	"likes": 340, 
	"vigencia": "Dec. 14 | 2018", 
	"imagen": "http://telcelbk.atomyc.in/static/temps/promo_28_min.jpg", 
	"premio": "", 
	"color": "c227b9", 
	"imagen_lg": "http://telcelbk.atomyc.in/static/temps/promo_28_min.JPG", 
	"linea_tres": "pop", 
	"shares": 120, 
	"bases": "", 
	"linea_dos": "de grupos", 
	"titulo": "TITULO", 
	"dinamica": "trivia", 
	"pk": 28, "terms": "", 
	"linea_uno": "concierto"}, 

	{"status": "publish", 
	"orden": 2, 
	"likes": 340, 
	"vigencia": "Oct. 04 | 2018", 
	"imagen": "http://telcelbk.atomyc.in/static/temps/promo_0_min.jpg", 
	"premio": "<p>dfghdfgh</p>", 
	"color": "c227b9", 
	"imagen_lg": "http://telcelbk.atomyc.in/static/temps/promo_29_min.jpg", 
	"linea_tres": "hasta adelante", 
	"shares": 120, 
	"bases": "<p>f</p><p>f</p><p>f</p><p>f</p>", 
	"linea_dos": "boletos", 
	"titulo": "TITULO", 
	"dinamica": "trivia", 
	"pk": 29, 
	"terms": "<p>dfghdfgh</p>", 
	"linea_uno": "rey leon"}
	]
}